spring:
  datasource:
#    url: 'jdbc:postgresql://localhost:5432/api-movie'
#    username: postgres
#    password: admin
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: off